### ISSUE TITLE
Failed to execute 'readAsText' on 'FileReader'

### ISSUE THREAD

**Issue by jpgarcia** [wkh237/react-native-fetch-blob#205] opened 2016-11-30 16:21 UTC
Hi Guys!,

I'm successfully uploading blobs to Firebase but after overriding the `XmlHttpRequest` I'm getting the following warning when debugging JS remotely:

```
Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
```
I think can be related to packager request or something like that but I'm not sure. I found a workaround for now but it will be nice to avoid that. I'm doing this before uploading:

```js
this.OriginalBlob = window.Blob
this.OriginalXMLHttpRequest = window.XMLHttpRequest
window.Blob = RNFetchBlob.polyfill.Blob
window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest
```
after uploading:

```js
window.Blob = this.OriginalBlob
window.XMLHttpRequest = this.OriginalXMLHttpRequest
```

My Uploader class looks like this:

```js
import RNFetchBlob from 'react-native-fetch-blob'
import { storage as firebaseStorage } from '@lib/firebase'

import EventEmitter from 'events'

class FirebaseUploader extends EventEmitter {

  constructor(bucket, fileName) {
    super()

    this.bucket = bucket
    this.fileName = fileName
  }

  uploadFromBase64(base64) {
    const type = 'application/octet-stream;BASE64'

    return Blob.build(base64, { type })
      .then(blob => {
        return this.uploadFromBlob(blob)
      })
  }

  uploadFromUri(uri) {
    return RNFetchBlob
      .fetch('GET', uri)
      .then(res => {
        return this.uploadFromBase64(res.data)
      })
  }

  uploadFromBlob(blob) {
    return new Promise((resolve, reject) => {
      var metadata = {
        cacheControl: 'public,max-age=1296000',
        contentType: 'image/png'
      }

      const uploadTask = firebaseStorage
        .ref(this.bucket)
        .child(this.fileName)
        .put(blob, metadata)

      uploadTask.on('state_changed', snapshot => {
        const { bytesTransferred, totalBytes } = snapshot
        const progress = (bytesTransferred / totalBytes) * 100
        this.emit('progress', progress)
      }, error => {
        blob.close()
        reject(error)
      }, () => {
        blob.close()
        resolve(uploadTask.snapshot.downloadURL)
      })
    })
  }
}

export default FirebaseUploader

```

### Context Versions
* **React Native**: 0.37.0
* **Node**: 7.1.0
* **Firebase**: 3.6.2
* **react-native-fetch-blob**: v0.10.1-beta.2

**Comment by wkh237** [comment] 2016-12-01 01:55
@jpgarcia , Thanks for reporting this issue. Your code looks fine, I'll try to find the problem 👍

**Comment by atlanteh** [comment] 2016-12-03 17:39
After upgrading to rnfb 0.10.0 I'm getting the same error for all post requests sent..(not related to firebase).

> Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.

React Native: 0.38.0
Node: 6.2.0
Firebase: 3.6.2
react-native-fetch-blob: v0.10.0

**Comment by jpgarcia** [comment] 2016-12-05 14:19
Hi guys, do you have any update on this?

thanks!

**Comment by bielcapanema** [comment] 2016-12-07 20:06
Same here 👎

**Comment by wkh237** [comment] 2016-12-08 00:11
still not be able to reproduce this problem, if someone can provide a sample project it'd be helpful 😅

**Comment by medlmichael** [comment] 2016-12-22 15:39
I can reproduce the issue.  I'm no expert but as a hunch it seems that once you use RNFetchBlob with Firebase for add an image to storage the issue occurs.  I have a component that once I use the uploaded my parent components standard fetch is being overridden.  I've tried switch to 0.9.5, 0.10 including betas the warning pops up.  Freezes my app but that might be a side effect.

**Comment by mz21** [comment] 2017-01-21 19:38
I think this happens because RNFetchBlob and the default fetch library can have strange interactions.

RNFB suggests wrapping RNFetchBlob.fetch https://github.com/wkh237/react-native-fetch-blob#user-content-rnfetchblob-as-fetch

That fixed it for me.

**Comment by wkh237** [comment] 2017-02-10 11:25
I'm going to close this and related ones as @mz21 already provided a feasible solution. 

The cause is that RN's devtool intended to send an HTTP request via `WHATWG-fetch` after  `XMLHttpRequest` for some reason, but `WHATWG-fetch` does not compatible with our Blob implementation, as such it failed upon consuming a `blob` object.

IMO applying fetch replacement in debug mode would be a solution to this issue.

**Closed by wkh237** 2017-02-10 11:25 UTC
Labels: trouble shooting

**Comment by Pianist038801** [comment] 2017-07-29 13:36
@mz21  How can I wrap fetch? I still have the issue and am stuck with it.

**Comment by wkh237** [comment] 2017-07-30 15:40
please refer to the [wiki](https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API#user-content-fetch-replacement) it might be help.

**Comment by Pianist038801** [comment] 2017-07-30 17:40
@wkh237 
Extremely thanks. You saved my day. :)

**Comment by Naveen-ICARUS** [comment] 2017-09-14 09:07
hi
can any one send me the working sample code with fetch replacement. i'm struggling from past 2 days. it'll will great help.
thanks

**Comment by vitalikzyzych** [comment] 2017-10-20 09:24
Hello, this my example 
```
        //Binary
        var reader = new FileReader();
        var t = this;
        reader.addEventListener("loadend", function() {
            t.readEndpointMessage(reader.result);
        });
        reader.readAsArrayBuffer(message.data);
```
On browser side all works fine (`message.data` is **Blob** with _proto Blob).
But on RN side it working inappropriate (`message.data` is **Blob** with _proto Object).
I can see this error `Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.`
Can someone help me with this issue?
P.S. message is Websocket message

**Comment by jankarres** [comment] 2017-10-24 14:10
I can recommend the [solution from @wkh237](https://github.com/wkh237/react-native-fetch-blob/issues/205#issuecomment-318909875) above. Replacing the fetch method with RNFetchBlob works easily.
