### ISSUE TITLE
firebase createUserWithEmailAndPassword wrong error on ios

### ISSUE THREAD

**Issue by atlanteh** [wkh237/react-native-fetch-blob#130] opened 2016-09-17 19:54 UTC
We have firebase up and running in our app. We tried adding fetch-blob to add files to firebase storage.
However suddenly firebase started producing us wrong message on createUserWithEmailAndPassword.

Normally when we create a user with createUserWithEmailAndPassword, the Promise should reject with error.code "auth/email-already-in-use" when the email is already in use.
However when adding fetch-blob, firebase suddenly takes quite a few seconds to return and has error.code "auth/network-request-failed" . 
This happens only if the polyfill is added **and only in ios.**

Running the following code **twice** fails for us: 
```jsx
import firebase from '../Services/firebase'; // firebase with auth..
import RNFetchBlob from 'react-native-fetch-blob';

const polyfill = RNFetchBlob.polyfill;

window.XMLHttpRequest = polyfill.XMLHttpRequest;
window.Blob = polyfill.Blob;

const email = 'test@gmail.com';
const password = '123456';
const firebaseAuth = firebase.auth();
firebaseAuth.createUserWithEmailAndPassword(email, password)
.catch(err => {
    alert(error.code); // Should be "auth/email-already-in-use". Instead we get "auth/network-request-failed"
});
```
**Versions**
react-native-fetch-blob: 0.9.4
react-native: 0.32.0

**Comment by wkh237** [comment] 2016-09-18 01:10
Thanks for your reporting, I will look into this issue and update the status in this thread.

**Comment by wkh237** [comment] 2016-09-18 08:24
@atlanteh , I've confirmed that t reason why the error message inconsistency between Android and IOS is because IOS throws error when status code is not 2xx but Android does not, I've changed IOS implementation and published a new release `0.9.5-beta.3`, please try install the version and see if the problem got fixed 😄 

```
$ npm install --save react-native-fetch-blob@0.9.5-beta.3
$ react-native link
```

**Comment by atlanteh** [comment] 2016-09-18 15:42
Yes. It solves the problem :)

**Comment by wkh237** [comment] 2016-09-19 00:45
Great! Let's close this issue

**Closed by wkh237** 2016-09-19 00:45 UTC
Labels: beta, bug, ios, needs feedback
